version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: golang-ec2-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: golang-echo-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    # environment:
    #   DB_HOST: postgres
    #   DB_PORT: 5432
    #   DB_USER: postgres
    #   DB_PASSWORD: postgres
    #   DB_NAME: crud_db
    #   DB_SSLMODE: disable

volumes:
  pg_data:
