version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: golang-ec2-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend_network

  # golang-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: golang-echo-app
  #   restart: always
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - backend_network

  golang-app:
    image: radityaditoo/golang-echo-crud:latest
    container_name: golang-echo-app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend_network

volumes:
  pg_data:

networks:
  backend_network:
