name: CI for PRs

on:
  pull_request:
    branches:
      - main # Runs when a PR is created to main

jobs:
  build-and-test:
    name: Validate PR (Build Only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t radityaditoo/golang-echo-crud:latest .

      - name: Validate Build (Dry Run)
        run: echo "Build successful for PR. No push or deploy."
